openapi: 3.0.3

info:
  title: Component
  version: "1.0.0"
paths: {}
components:
  schemas:
    RegisterRq:
      type: object
      properties:
        username:
          type: string
          required: true
        password:
          type: string
          required: true
        fullname:
          type: string
          required: true
        email:
          type: string
          required: true
        role:
          type: string
          required: true

    LoginRq:
      type: object
      properties:
        username:
          type: string
          required: true
        password:
          type: string
          required: true

    GetUserFilter:
      type: object
      properties: {}#TODO: for admin

    UpdateUserRq:
      type: object
      properties:
        fullname:
          type: string
        gender:
          type: string
        dob:
          type: number
        address:
          type: object
          allOf:
            - $ref: './common.yaml#/components/schemas/Address'
        email:
          type: string
        phone:
          type: string
        avatar:
          type: string

    GetTutorFilter:
      type: object
      properties:
        fee:
          type: string
          description: min,max
        subject:
          type: string
          description: multiple ','
        level:
          type: string
        gender:
          type: string
        availableTime:
          type: string
        location:
          type: array
          items:
            allOf:
              - $ref: './common.yaml#/components/schemas/Address'
        distance:
          type: string
    UpdateTutorRq:
      type: object
      properties:
        availableTime:
          type: string
        subjects:
          type: array
          allOf:
            - $ref: './common.yaml#/components/schemas/TutorSubject'
        teachingLocations:
          type: array
          allOf:
            - $ref: './common.yaml#/components/schemas/Address'
        selfDescription:
          type: string



