openapi: 3.0.3

info:
  title: Component
  version: "1.0.0"
paths: {}
components:
  schemas:
    RegisterRq:
      type: object
      properties:
        username:
          type: string
          required: true
        password:
          type: string
          required: true
        email:
          type: string
          required: true
        role:
          type: integer
          required: true
    LoginRq:
      type: object
      properties:
        username:
          type: string
          required: true
        password:
          type: string
          required: true
