openapi: 3.0.3

info:
  title: Component
  version: "1.0.0"
paths: {}
components:
  schemas:
    LoginRs:
      type: object
      properties:
        accessToken:
          type: string
    GetCurrentUserRs:
      type: object
      properties:
        username:
          type: string
        fullname:
          type: string
        avatar:
          type: string
          description: url link
