openapi: 3.0.3

info:
  title: Component
  version: "1.0.0"
paths: {}
components:
  schemas:
    RegisterRs:
      type: object
      properties:
        accessToken:
          type: string
    LoginRs:
      type: object
      properties:
        accessToken:
          type: string
    GetCurrentUserRs:
      type: object
      properties:
        username:
          type: string
        fullname:
          type: string
        role:
          type: integer
        avatar:
          type: string
          description: url link
