openapi: 3.0.0
servers:
  - description: Local - For dev purpose only
    url: http://127.0.0.1:8080
info:
  description: BkConnect API
  version: "1.0.0"
  title: BkConnect API
  contact:
    email: phunguyen3107@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: non-logged
    description: Non-logged User
  - name: logged
    description: Logged User
  - name: admin
    description: Admin only
  - name: tutor
    description: For Tutor only
  - name: student
    description: Student only

paths:
  /session/register:
    post:
      tags:
        - non-logged
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schema/request.yaml#/components/schemas/RegisterRq'
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: './schema/response.yaml#/components/schemas/RegisterRs'

  /session/login:
    post:
      tags:
        - non-logged
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schema/request.yaml#/components/schemas/LoginRq'
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: './schema/response.yaml#/components/schemas/LoginRs'
  /session/getCurrentUser:
    get:
      tags:
        - logged
      summary: Get current user
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: './schema/response.yaml#/components/schemas/GetCurrentUserRs'

