name: Deploy API specification on Github Page

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api-specification.yml
      - openapi/**

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install swagger-cli and redoc-cli
        run: npm install -g swagger-cli redoc-cli

      - name: Convert multiple .yaml file to single .json file
        run: swagger-cli bundle -o target/openapi/openapi.json openapi/specification.yaml

      - name: Generate Swagger UI
        run: redoc-cli build -o target/openapi/index.html target/openapi/openapi.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/openapi/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
